apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  DB_CONNECTION_STRING: {{ .Values.DB_CONNECTION_STRING | b64enc }}
  DB_CONNECTION_STRING_PULSE: {{ .Values.DB_CONNECTION_STRING_PULSE | b64enc }}
  SesameBasicAuth: {{ .Values.SesameBasicAuth | b64enc }}
  SECRET_ENCRIPTION_KEY: {{ .Values.SECRET_ENCRIPTION_KEY | b64enc }}
